version: "3.8"

services:
  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    build:
      context: docker
      dockerfile: ./php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/var/www/
    networks:
      - tournaments

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:rw
      - ./docker/php-fpm/php.ini:/etc/php/8.1/cli/php.ini
    depends_on:
      - php-fpm
    networks:
      - tournaments

  database:
      image: 'mysql:latest'
      container_name: ${COMPOSE_PROJECT_NAME}_database
      command: --max-allowed-packet=500M
      volumes:
        - "./docker/db/data:/var/lib/mysql"
        - "./docker/db/logs:/var/log/mysql"
        - "./docker/db:/etc/mysql/conf.d"
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_USER: nonroot
        MYSQL_PASSWORD: nonroot
        MYSQL_DATABASE: tournaments
      ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '3306:3306'
      networks:
        - tournaments


networks:
  tournaments:
    driver: bridge

volumes:
  database:
